.github/workflows/check-file-format.yaml
.github/workflows/check-markdown-format.yaml
.github/workflows/check-python-black-format.yaml
.github/workflows/check-python-flake-rules.yaml
.github/workflows/check-terraform-format.yaml
.github/workflows/cicd-pipeline.yaml
.github/workflows/cloc-repository.yaml
.github/workflows/orchestrate-bootstrap.yaml
.github/workflows/run-bootstrap.yaml
.github/workflows/scan-dependencies.yaml
.github/workflows/scan-secrets.yaml
.github/workflows/validate-terraform.yaml
infrastructure/stacks/github-runner/uec-github-runner-iam-services.json
scripts/bootstrapper.sh

Adds some missing permissions to github runner role and adds github workflow to keep tf state and github resources in synch
---
- [x ] I confirm that neither PII/PID nor sensitive data are included in this PR and the codebase changes.

DR-371 Add boot strap action

---

.github/workflows/cicd-pipeline.yaml
.gitignore
scripts/config/sonar-scanner.properties
scripts/reports/perform-static-analysis.sh

DR-999 Perform static analysis

---

scripts/sql/aurora_extract_scripts/README.md
scripts/sql/aurora_extract_scripts/pharmacy-age-ranges.sql
scripts/sql/aurora_extract_scripts/pharmacy-finder.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-alignments.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-attributes.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-dispositions.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-endpoints.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-genders.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-phones.sql
scripts/sql/aurora_extract_scripts/pharmacy-service-referral-roles,sql
scripts/sql/aurora_extract_scripts/pharmacy-servicedayopenings.sql
scripts/sql/aurora_extract_scripts/pharmacy-services.sql
scripts/sql/aurora_extract_scripts/pharmacy-specified-dates-times.sql
scripts/sql/aurora_extract_scripts/pharmacy_service_referrals.sql
scripts/sql/aurora_extract_scripts/pharmacy_sgsds.sql

The scripts are used to identify services linked by ODS code and to extract key service related data 
The data produced by scripts should be exported to csv and imported into a spreadsheet to help build the new data schema
These files will serve no purpose once that exercise is complete so can be removed later
The README is included to make that clear
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) or any other sensitive data in this PR (Pull Request) and the codebase changes. We will remove any PR that do contain any sensitive information. We really appreciate …

DR-421 Sql scripts to extract service data for subset of pharmacy service types

---

scripts/sql/aurora_extract_scripts/sample-healthcareservice-json.sql

SQL script that will generate json data to match the DoS healthcareService and serviceProfile json
---

DR-468 SQL script for healthcareService json

---

scripts/sql/aurora_extract_scripts/sample-healthcareservice-json.sql

Updated the pharmacy healthcareservices script with refined rules to consolidate pharmacies
---

DR-492 Updated sql for pharmacy import

---

scripts/config/.gitleaks.toml

Addition of AWS account number for implementation of Lambda layering. The account number is publicly available and so is safe to store in the code repository.
---

DR-999 Addition of allow rule

---

.github/workflows/pipeline-infrastructure-cleardown.yaml

PR to plug in the if statement for the trigger and terraform jobs (Action set to plan for testing purposes)
---

DR-419 Add terraform jobs

---

.github/workflows/cleardown-terraform-state.yaml
.github/workflows/pipeline-infrastructure-cleardown.yaml
.github/workflows/validate-terraform.yaml
scripts/cleardown-terraform-state.sh

PR to parse in the workspace reference to the destroy workflow upon branch deletion and delete terraform state & lock files for the current workspace. 
required in order to cleanse the development environments after use
---

DR-419 Cleardown infra and terraform state

---

.github/workflows/cleardown-terraform-state.yaml

DR-429 Bugfix tfstate cleardown

---

README.md

DR-999 Test del action

---

infrastructure/stacks/application/misc/step-function.json
scripts/git/git-config-set-up.sh

Added Step Functions config code in JSON to agreed location
Changed git hook setup script to disable tracking of file permissions change 
---

DR-481 Definition file data

---

tests/integration/behave.ini
tests/integration/environment.py

DR-999 Fix to integration tests after move to sm

---

.github/workflows/cleardown-terraform-state.yaml
scripts/cleardown-terraform-state.sh

Parameterise tf bucket name and lock table
---

DR-562 Parameterise tf bucket name and lock table

---

infrastructure/dev.tfvars
infrastructure/network.tfvars
infrastructure/stacks/network/data.tf
infrastructure/stacks/network/variables.tf
infrastructure/stacks/network/vpc.tf
infrastructure/test.tfvars

Set up a vpc -dynamically derive azs and associated private subnets
---

DR-318 Initial vpc set up

---

scripts/org_data_load/org_data_load.py

DR-533 Organization data load

---

.github/workflows/pipeline-deploy-app-test.yaml
scripts/app-build-deploy.sh

DR-595 Plug in integration test script

---

application/organisations-data-manager/app.py
application/organisations-data-manager/service.py
application/organisations-data-manager/test/events/mock_proxy_delete_event.json
application/organisations-data-manager/test/events/mock_proxy_get_event.json
application/organisations-data-manager/test/events/mock_proxy_post_event.json
application/organisations-data-manager/test/events/mock_proxy_put_event.json
application/organisations-data-manager/test/requirements.txt
application/organisations-data-manager/test/test_app.py
application/organisations-data-manager/test/test_service.py
scripts/integration-tests.sh
tests/integration/config/config_dev.ini
tests/integration/data_json/organisation_affiliations_post_body.json
tests/integration/data_json/organisation_post_body.json
tests/integration/features/healthcare_services.feature
tests/integration/features/locations.feature
tests/integration/features/organisations.feature
tests/integration/features/organisations_affiliations.feature

Task/DR-565 Organisation CRUD lambda

---

infrastructure/common/common-variables.tf
infrastructure/stacks/network/variables.tf
infrastructure/stacks/network/vpn.tf

Switch protocol for vpn to tcp
---

DR-631 Change protocol to tcp

---

.github/workflows/action-infrastructure-cleardown.yaml
.github/workflows/derive-terraform-workspace-from-branch-name.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-infrastructure-cleardown.yaml

A pipeline designed to cleardown branch build resources in test account and corresponding terraform state
---

DR-563 Workflow to delete workspaced resources in test

---

.github/workflows/action-infrastructure-cleardown.yaml
.github/workflows/derive-terraform-workspace-from-branch-name.yaml

DR-563 Remove ref to task branch from checkout

---

.github/workflows/action-infrastructure-cleardown.yaml

DR-563 Remove redundant constraint

---

application/questionnaires-data-manager/app.py
application/questionnaires-data-manager/service.py
application/questionnaires-data-manager/test/events/mock_proxy_delete_event.json
application/questionnaires-data-manager/test/events/mock_proxy_get_event.json
application/questionnaires-data-manager/test/events/mock_proxy_post_event.json
application/questionnaires-data-manager/test/events/mock_proxy_put_event.json
application/questionnaires-data-manager/test/requirements.txt
application/questionnaires-data-manager/test/test_app.py
application/questionnaires-data-manager/test/test_service.py
tests/integration/features/questionnaires.feature

Update crud functions and unit test for Questionnaires data manager service.
---

DR-576 Implement crud functions

---

tests/integration/environment.py
tests/integration/requirements.txt
tests/integration/steps/data_steps.py
tests/integration/utilities/api.py

DR-608 Refactoring after setup

---

infrastructure/stacks/application/apig-healthcare-services.tf
infrastructure/stacks/application/apig-locations.tf
infrastructure/stacks/application/apig-organisation-affiliations.tf
infrastructure/stacks/application/apig-organisations.tf
infrastructure/stacks/application/apig-questionnaire-responses.tf
infrastructure/stacks/application/apig-questionnaires.tf

Make creation of lambda permssions dependent on prior creation of  corresponding lambda
---

DR-646 Add depends on

---

tests/integration/features/healthcare_services.feature
tests/integration/features/locations.feature
tests/integration/features/organisations.feature
tests/integration/features/organisations_affiliations.feature
tests/integration/features/questionnaire_responses.feature
tests/integration/features/questionnaires.feature
tests/integration/steps/common_steps.py
tests/integration/steps/data_steps.py

DR-665 Added allure tags to integration tests

---

.github/workflows/pipeline-deploy-app-develop.yaml

DR-596 Plug in metadata flow

---

scripts/functions/check-branch-name.sh
scripts/functions/check-commit-message.sh
scripts/functions/git-functions.sh
scripts/functions/test-git-functions.sh

DR-687 Improve validation of git commit message and branch names

---

.github/workflows/pipeline-deploy-app-develop.yaml
scripts/githooks/front-end-npm-lint-pre-commit.sh

DR-596 Integrate qual check

---

.github/workflows/pipeline-deploy-app-develop.yaml

DR-596 Integrate with dos management unit test workflow

---

.github/workflows/pipeline-deploy-app-develop.yaml
scripts/v2/derive-workspace.sh

DR-596 move to v0.2 of workflows

---

.github/workflows/action-infrastructure-cleardown.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml

DR-5968 Patch teardown pipeline

---

.github/workflows/pipeline-deploy-app-develop.yaml

DR-5969 Refactor infra deploy

---

application/service_data_load/service_data_load.py
application/service_data_load/test/test_service_data_load.py

DR-669 Opendaytime data load

---

.github/workflows/action-infrastructure-stack.yaml
.github/workflows/manual-deploy-tagged-code.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-app-test.yaml
.github/workflows/pipeline-tag-deploy-test.yaml

DR-774 Refactored test deploy pipelines

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-tag-deploy-test.yaml

DR-664 Plug in common slack flow

---

.github/workflows/pipeline-deploy-app-develop.yaml

DR-771 Refactor deployment of support tools infra

---

.github/workflows/pipeline-infrastructure-cleardown-dev.yaml

Fix pipeline-infrastructure-cleardown-dev.yaml 
removed  github_environment: and branch_name: from uec-dos-service-management/.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
https://nhsd-jira.digital.nhs.uk/browse/DR-798
- [X This PR is a result of pair or mob programming
---

DR-7981 Pipeline cleardown dev

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml

Format the stacks array consistently within pipeline-infrastructure-cleardown-dev.yaml
https://nhsd-jira.digital.nhs.uk/browse/DR-798
---

DR-7981 Pipeline cleardown dev - format stack arrays consistently

---

.github/workflows/pipeline-infrastructure-cleardown-test.yaml

Pipeline infrastructure cleardown test yaml. Same as dev yaml but with some minor amendments to reflect the test environment.
https://nhsd-jira.digital.nhs.uk/browse/DR-798
---

DR-7987 Pipeline  infrastructure cleardown test yaml

---

README.md

DR-630 Minor readme change

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-app-test.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-manual-deploy-tagged-code.yaml
.github/workflows/pipeline-tag-deploy-test.yaml

1 - Tag version increment from v0.14 to v0.16
2 - Check listed pipeline runtimes and override if required.
3 - Test timeout override functionality.
As part of this ticket was to check the listed pipeline runtimes are well below the current default 5 minute threshold. All within accepted threshold so no code changes required.
Tested the time override which is documented in the ticket. https://nhsd-jira.digital.nhs.uk/browse/DR-834
https://nhsd-confluence.digital.nhs.uk/display/DR/Reusable+Workflows+Default+Timeout
---
To ensure the utmost confidentiality and protect your and others privacy, we kindly ask you to NOT including [PII (Personal Identifiable Information) / PID (Personal Identifiable Data)](https://digital.nhs.uk/data-and-information/keeping-data-safe-and-benefitting-the-public) …

DR-834 pipeline timeout parameter and tag version increment

---

.github/workflows/pipeline-deploy-app-test.yaml
infrastructure/stacks/data_migration/locations_lambda.tf
infrastructure/stacks/data_migration/org_data_load_lambda.tf
infrastructure/stacks/data_migration/orgaffiliation_lambda.tf
infrastructure/stacks/data_migration/service_data_load_lambda.tf

DR-907 Updating the pandas python version

---

.coveragerc
data_migration/service_data_load/service_data_load.py
data_migration/service_data_load/test/test_service_data_load.py

task/DR-906 Service data load lambda fix

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-app-test.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-manual-deploy-tagged-code.yaml
.github/workflows/pipeline-tag-deploy-test.yaml
application/healthcare-services-data-manager/app.py
infrastructure/stacks/github-runner/data.tf
infrastructure/stacks/github-runner/role.tf

DR-920 GitHub runner s3 access

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-app-test.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-manual-deploy-tagged-code.yaml
.github/workflows/pipeline-tag-deploy-test.yaml

DR-898 Switch latest tag

---

.github/workflows/pipeline-infrastructure-cleardown-dev.yaml

DR-957 Cleardown redundant artefact

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-app-int.yaml
.github/workflows/pipeline-deploy-app-test.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-manual-deploy-tagged-code.yaml
.github/workflows/pipeline-tag-deploy-int.yaml
.github/workflows/pipeline-tag-deploy-test.yaml
application/healthcare-services-data-manager/app.py
infrastructure/dev.tfvars
infrastructure/domain-test.tfvars

DR-929 Draft deploy to integration workflow

---

infrastructure/stacks/github-runner/uec-github-runner-iam-services.json

DR-929 Enable runner to update role policy

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml
.github/workflows/pipeline-deploy-app-develop.yaml
.github/workflows/pipeline-deploy-app-int.yaml
.github/workflows/pipeline-deploy-app-test.yaml
.github/workflows/pipeline-infrastructure-cleardown-dev.yaml
.github/workflows/pipeline-infrastructure-cleardown-test.yaml
.github/workflows/pipeline-manual-deploy-tagged-code.yaml
.github/workflows/pipeline-tag-deploy-int.yaml
.github/workflows/pipeline-tag-deploy-test.yaml

DR-1000 Change tag to latest

---

infrastructure/common/common-variables.tf
infrastructure/preprod.tfvars
infrastructure/prod.tfvars
infrastructure/stacks/network/variables.tf

DR-963 Prod and preprod tfvars

---

infrastructure/preprod.tfvars
infrastructure/prod.tfvars
scripts/create-lambda-layer.sh

DR-10131 Request lambda layer script

---

.github/workflows/pipeline-deploy-app-preprod-prod.yaml

workflow to deploy to Pre-Prod / Prod environments
---

DR-1013 Implement prod workflow

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml

DR-1030 No github runner required in int

---

.github/workflows/pipeline-deploy-account-infrastructure.yaml

DR-1030 Restore github runner to int flow

---

.github/workflows/pipeline-truncate-workflow-history.yaml

Adding pipeline for truncating action history which utilities the shared workflow in DoS management.
---

DR-978 Add pipeline for truncating action history

---

infrastructure/data_migration.tfvars
infrastructure/stacks/data_migration/database_populator_lambda.tf
infrastructure/stacks/data_migration/locations_lambda.tf
infrastructure/stacks/data_migration/ods_location_comparator.tf
infrastructure/stacks/data_migration/org_data_load_lambda.tf
infrastructure/stacks/data_migration/orgaffiliation_lambda.tf
infrastructure/stacks/data_migration/questionnaire_response_populator_lambda.tf
infrastructure/stacks/data_migration/s3_datasource.tf
infrastructure/stacks/data_migration/service_data_load_lambda.tf
infrastructure/stacks/data_migration/variables.tf

DR-1122 Parameterise bucket name

---

.github/CODEOWNERS

DR-1183 Set code ownership
